remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Genshin AR Calculator]
description: [Website to test and use Genshin AR Calculator example]
